FROM python:3

RUN mkdir code

WORKDIR code

RUN git clone -b develop https://github.com/ppuertocrem/obnl.git
RUN pip install --no-cache-dir -r obnl/requirements.txt

RUN cd obnl && python setup.py install

RUN git clone https://github.com/ppuertocrem/ict-demo-GA.git

ENTRYPOINT ["/usr/local/bin/python", "obnl/obnl/server.py"]
